<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>HongYeValidator</AssemblyName>
    <RootNamespace>HongYeValidator</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>runtime\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SchStateLib">
      <HintPath>runtime\SchStateLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
